services:
  - type: web_service
    name: devbox-server
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: "4000"
      - key: NODE_ENV
        value: "production"
      - key: DATABASE_URL
        value: ""
      - key: JWT_SECRET
        value: ""
      - key: VITE_API_URL
        value: ""
